{"name": "Успешный вход под существующим пользователем", "status": "passed", "attachments": [{"name": "stdout", "source": "59e2bd48-1166-48ee-9864-f1440a6021e3-attachment.txt", "type": "text/plain"}], "start": 1749813353304, "stop": 1749813353728, "uuid": "29a165ab-05d7-4d82-84f4-fd7d027f6eee", "historyId": "161bfae03c497bc14a1d3becfb28eda7", "testCaseId": "161bfae03c497bc14a1d3becfb28eda7", "fullName": "tests.test_login_user.TestLoginUser#test_auth_with_valid_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-5MH90VS"}, {"name": "thread", "value": "2380-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}