{"name": "Ошибка входа с неверным паролем", "status": "passed", "attachments": [{"name": "stdout", "source": "49419dbf-61de-46b9-a574-7231b730f057-attachment.txt", "type": "text/plain"}], "start": 1749813354996, "stop": 1749813355416, "uuid": "79310fe0-f62c-48ec-8b93-1510df7b22a0", "historyId": "94b475b8696fd8c415c17ece03df27c2", "testCaseId": "94b475b8696fd8c415c17ece03df27c2", "fullName": "tests.test_login_user.TestLoginUser#test_auth_with_wrong_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-5MH90VS"}, {"name": "thread", "value": "2380-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}